version: '3.8'

services:
  web:
    build: .
    command: python manage.py run -h 0.0.0.0 && python manage.py create_db && python manage.py seed_db
    ports:
      - "5000:5000"
    volumes:
      - .:/app/
    env_file:
      - ./.env.dev
    # depends_on:
    #   - database

  db:
    image: postgres:13
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=cats

volumes:
  pgdata: